### ISSUE TITLE
Issues with async `main` entry point

### ISSUE THREAD

**Issue by Gitii** [sharpninja/WindowsAppSdkHost#3]
Hi,

as noted in the readme:
```
[STAThread]
public static void Main(string[] args)
{
    var builder = new WindowsAppSdkHostBuilder<App>();

...

    var app = builder.Build();

    app.StartAsync().GetAwaiter().GetResult();
}
```

this works fine, **but** when turned into an `async` method...
```
[STAThread]
public async static Task Main(string[] args)
{
...
    app.StartAsync().GetAwaiter().GetResult();
}
```
or
```
[STAThread]
public async static Task Main(string[] args)
{
...
    await app.StartAsync();
}
```
... `WebView2` and `automation ui` break: either `WebView2` doesn't render at all or crashes. `automation ui` just stops working (for example, using `inspect.exe` no ui elements can be found).

This isn't an issue per se, but I would like to understand why this happens - especially because all other parts of winui 3 continue to work fine. I assume it might be a threading thing but I am not sure.
I created a reproduction repo with three different versions (using preprocessor directives) of `main`.

`V1`: working, no changes, like in the readme
`V2`: nothing rendered, no crash, ui automation doesn't work
`V3`: crash at startup (in webview), ui automation doesn't work

https://github.com/Gitii/WindowsAppSdkHostWithBrowser

Would be great if someone could shed some light on this,

best regards

**Comment by sharpninja** [comment]
The issue is with WebView2.  It absolutely must have its core running on the STA thread.  When you apply `async task` to the main menu, it will always pull a thread from the TaskScheduler's threadpool to call the Main method in.
